### ISSUE TITLE
FEATURE: simple lists of domains based on HTTP error codes

### ISSUE THREAD

**Issue by mitchellkrogza** [funilrys/funceble#112]
Managed to get a lot of data out of the results.txt file for sorting through.

Would be great to have in the root of  output folder `HTTP_Analytic` simple files with no commenting and only domain names for example.

`HTTP_Analytic/404.txt`
`HTTP_Analytic/403.txt`
`HTTP_Analytic/410.txt`

etc etc

**Comment by funilrys** [comment]
You mean that I should split the results according to their http code ? Or add an option to split the results according to http codes ?

**Comment by mitchellkrogza** [comment]
I think when we activate `--plain` it can possibly produce individual txt files based on their error code, then cherry picking what we want to remove first will be a breeze.

**Comment by funilrys** [comment]
Fixed with https://github.com/funilrys/funceble/commit/f77ce28f3d298fdaaafb3659fb6478ab6b2561d6.

P.S: Please **DO NOT** close this issue manually. This issue is gonna be closed automatically once https://github.com/funilrys/funceble/commit/f77ce28f3d298fdaaafb3659fb6478ab6b2561d6 will be merged to [`master`](https://github.com/funilrys/funceble/tree/master).
