### ISSUE TITLE
SPECIAL (additions)

### ISSUE THREAD

**Issue by mitchellkrogza** [funilrys/funceble#172]
Please add to filter options.

`tumblr.com`

Can search for "nothing here"

![screen shot 2017-09-22 at 5 09 04 pm](https://user-images.githubusercontent.com/9961541/30751153-cc3d22ba-9fb8-11e7-80ed-378af6bcfd26.png)

**Comment by smed79** [comment]
Is the `--filter` option can be used to check for parked domains?

**Comment by funilrys** [comment]
@SMed79 No there's a confusion here :+1: 

`--filter` gonna regex search domain which means: 

```
./funceble --filter '\.blogspot\.' -f MyAwesomeHostsFile
```
**OR**
```
./funceble --filter '.blogspot.' -f MyAwesomeHostsFile`
```

Will test only all Blogspot domains.


What @mitchellkrogza is talking about is the **SPECIAL** case which gonna be documented into the wiki but the only documentation can be found [here](https://slack-files.com/T5EJ40THR-F776JRUCF-b97859e3a7) for now.

**Comment by funilrys** [comment]
Fixed with https://github.com/funilrys/funceble/commit/47eb2b725a8210b19180bf1c2e6697d6dd49c72b.

P.S: Please **DO NOT** close this issue manually. This issue is gonna be closed automatically once https://github.com/funilrys/funceble/commit/47eb2b725a8210b19180bf1c2e6697d6dd49c72b will be merged to [`master`](https://github.com/funilrys/funceble/tree/master).
