### ISSUE TITLE
Introduction of skyrock.com into SPECIAL

### ISSUE THREAD

**Issue by smed79** [funilrys/funceble#173]
Hi, 

Introduction of `skyrock.com` into `SPECIAL`
e.g 
- `http://funceble.skyrock.com/`
- http://i.imgur.com/xQI6MUb.png

**Comment by funilrys** [comment]
Fixed with https://github.com/funilrys/funceble/commit/f1adfd941fd4e03d490c2bd97d6729b6e9d9d016.

P.S: Please **DO NOT** close this issue manually. This issue is gonna be closed automatically once https://github.com/funilrys/funceble/commit/f1adfd941fd4e03d490c2bd97d6729b6e9d9d016 will be merged to [`master`](https://github.com/funilrys/funceble/tree/master).
