### ISSUE TITLE
Introduction of wordpress.com into SPECIAL

### ISSUE THREAD

**Issue by smed79** [funilrys/funceble#174]
Introduction of `wordpress.com` into SPECIAL

- `http://funceble.wordpress.com/`
- http://i.imgur.com/ONRpsvj.png

**Comment by funilrys** [comment]
Fixed with https://github.com/funilrys/funceble/commit/bf1cd9b4c67e5bc574647c46db1205a7befa0095.

P.S: Please **DO NOT** close this issue manually. This issue is gonna be closed automatically once https://github.com/funilrys/funceble/commit/bf1cd9b4c67e5bc574647c46db1205a7befa0095 will be merged to [`master`](https://github.com/funilrys/funceble/tree/master).
