### ISSUE TITLE
nslookup command not found on Ubuntu Linux

### ISSUE THREAD

**Issue by xxcriticxx** [funilrys/funceble#65]
i think you should check for `dnsutils` during installation my linux came with out `nslookup`

**Comment by funilrys** [comment]
@xxcriticxx Thanks for using funceble and for reporting this issue.

I just fixed this issue with https://github.com/funilrys/funceble/commit/0e1df83d715c540caa4a71d2bf29d99f0bb9e82a. 

It's gonna be in the next release.

Thanks again and have a nice day/night.

Cheers,
Nissar

P.S: Please **DO NOT** close this issue manually. This issue is gonna be closed automatically once https://github.com/funilrys/funceble/commit/0e1df83d715c540caa4a71d2bf29d99f0bb9e82a will be merged to [master](https://github.com/funilrys/funceble/tree/master).
