### ISSUE TITLE
uninstall option

### ISSUE THREAD

**Issue by xxcriticxx** [funilrys/funceble#67]
i don't see uninstall/remove option. do you have any plans for this in the future?

**Comment by funilrys** [comment]
Didn't think about it @xxcriticxx :+1:

**Comment by funilrys** [comment]
@xxcriticxx Thanks for using funceble and for requesting this feature.

I just fixed this issue with https://github.com/funilrys/funceble/commit/def3ba404188236e34aa58740233540b039b7522. 

It's gonna be in the next release.



Thanks again and have a nice day/night.

Cheers,
Nissar

P.S: Please **DO NOT** close this issue manually. This issue is gonna be closed automatically once https://github.com/funilrys/funceble/commit/def3ba404188236e34aa58740233540b039b7522 will be merged to [master](https://github.com/funilrys/funceble/tree/master).
